--------------------------------------------------------
--  文件已创建 - 星期二-十二月-11-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table TYPE_
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."TYPE_" 
   (	"ID" NUMBER, 
	"NAME_" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TEACHERS
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."TEACHERS" 
   (	"TEA_ID" NUMBER, 
	"TEA_PW" VARCHAR2(30 BYTE), 
	"TEA_NAME" VARCHAR2(20 BYTE), 
	"TEA_SEX" VARCHAR2(5 BYTE), 
	"TEA_AGE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."STUDENTS" 
   (	"STU_ID" NUMBER, 
	"STU_PW" VARCHAR2(30 BYTE), 
	"STU_NAME" VARCHAR2(20 BYTE), 
	"STU_SEX" VARCHAR2(5 BYTE), 
	"STU_AGE" NUMBER, 
	"STU_MAJOR" VARCHAR2(50 BYTE), 
	"STU_CLASS" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SCORE
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."SCORE" 
   (	"COU_ID" NUMBER, 
	"STU_ID" NUMBER, 
	"COU_NUM" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "C##SCOTT"."COURSES" 
   (	"TEA_ID" NUMBER, 
	"COU_ID" NUMBER, 
	"COU_NAME" VARCHAR2(30 BYTE), 
	"COU_TIME" VARCHAR2(20 BYTE), 
	"COU_CTIME" VARCHAR2(20 BYTE), 
	"COU_FEN" NUMBER, 
	"COU_SNUM" NUMBER, 
	"COU_LNUM" NUMBER, 
	"STATE" VARCHAR2(10 BYTE), 
	"T_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##SCOTT.TYPE_
SET DEFINE OFF;
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (1,'专业任选');
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (2,'专业必选');
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (3,'专业限选');
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (4,'通识任选');
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (5,'通识必选');
Insert into C##SCOTT.TYPE_ (ID,NAME_) values (6,'人文必选');
REM INSERTING into C##SCOTT.TEACHERS
SET DEFINE OFF;
Insert into C##SCOTT.TEACHERS (TEA_ID,TEA_PW,TEA_NAME,TEA_SEX,TEA_AGE) values (101,'123123','花花test修改','男',33);
Insert into C##SCOTT.TEACHERS (TEA_ID,TEA_PW,TEA_NAME,TEA_SEX,TEA_AGE) values (106,'123123123','更新测试','男',99);
Insert into C##SCOTT.TEACHERS (TEA_ID,TEA_PW,TEA_NAME,TEA_SEX,TEA_AGE) values (17777,'123123','测试增加教师','女',16);
Insert into C##SCOTT.TEACHERS (TEA_ID,TEA_PW,TEA_NAME,TEA_SEX,TEA_AGE) values (8877,'123123','test老师','男',33);
REM INSERTING into C##SCOTT.STUDENTS
SET DEFINE OFF;
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (12312,'123123','周1','女',60,'通信工程','8班');
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (456456,'123123','测试增加学生','男',12,'通讯工程','一班');
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (17018384,'123123','张2','男',20,'通信工程','8班');
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (172018353,'123123','杨秋2','女',134,'通信工程','8班');
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (172018434,'123123','周2','女',18,'test','2班');
Insert into C##SCOTT.STUDENTS (STU_ID,STU_PW,STU_NAME,STU_SEX,STU_AGE,STU_MAJOR,STU_CLASS) values (162011322,'123123','吴柱豪','男',22,'计算机科学与技术','八班');
REM INSERTING into C##SCOTT.SCORE
SET DEFINE OFF;
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (123,456456,100);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (223,456456,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (766,456456,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1001,456456,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1010,172018434,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (766,172018434,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1010,456456,100);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (104,12312,100);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (123,12312,100);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (223,12312,12);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (333,12312,12);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (766,12312,13);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1001,12312,12);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1001,17018384,12);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1008,12312,14);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1010,12312,100);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (104,456456,null);
Insert into C##SCOTT.SCORE (COU_ID,STU_ID,COU_NUM) values (1001,172018434,null);
REM INSERTING into C##SCOTT.COURSES
SET DEFINE OFF;
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,123333,'oracle','12-18周','周一1-3节',2,123,0,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,113333,'test','12-18周','周一1-3节',2,123,0,'授课中',3);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,233,'12','21-12周','周四2-3节',12,12,0,'授课中',5);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,104,'大数据test','1-18周','周五8-9节',2,100,3,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,123,'jsp','1-18周','周四8-10节',3,100,4,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,223,'心理与健康','1-18周','周二4-5节',1,100,4,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,333,'c','1-18周','周二4-5节',4,60,0,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,766,'人文基础','1-18周','周二1-2节',2,123,3,'授课中',6);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,1001,'java','9-18周','周三10-12节',3,30,2,'已结课',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,1008,'python','1-18周','周五8-9节',4,30,0,'授课中',1);
Insert into C##SCOTT.COURSES (TEA_ID,COU_ID,COU_NAME,COU_TIME,COU_CTIME,COU_FEN,COU_SNUM,COU_LNUM,STATE,T_ID) values (101,1010,'css','1-18周','周五1-2节',4,100,4,'授课中',1);
--------------------------------------------------------
--  DDL for Index TYPES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."TYPES_PK" ON "C##SCOTT"."TYPE_" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TEACHERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."TEACHERS_PK" ON "C##SCOTT"."TEACHERS" ("TEA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."STUDENTS_PK" ON "C##SCOTT"."STUDENTS" ("STU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SCORE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."SCORE_PK" ON "C##SCOTT"."SCORE" ("COU_ID", "STU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COURSES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##SCOTT"."COURSES_PK" ON "C##SCOTT"."COURSES" ("COU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table TYPE_
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."TYPE_" ADD CONSTRAINT "TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."TYPE_" MODIFY ("NAME_" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."TYPE_" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TEACHERS
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."TEACHERS" ADD CONSTRAINT "TEACHERS_PK" PRIMARY KEY ("TEA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."TEACHERS" MODIFY ("TEA_AGE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."TEACHERS" MODIFY ("TEA_SEX" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."TEACHERS" MODIFY ("TEA_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."TEACHERS" MODIFY ("TEA_PW" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."TEACHERS" MODIFY ("TEA_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDENTS
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."STUDENTS" ADD CONSTRAINT "STUDENTS_PK" PRIMARY KEY ("STU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_CLASS" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_MAJOR" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_AGE" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_SEX" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_PW" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."STUDENTS" MODIFY ("STU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCORE
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."SCORE" ADD CONSTRAINT "SCORE_PK" PRIMARY KEY ("COU_ID", "STU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."SCORE" MODIFY ("STU_ID" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."SCORE" MODIFY ("COU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."COURSES" ADD CONSTRAINT "COURSES_PK" PRIMARY KEY ("COU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_LNUM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_SNUM" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_FEN" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_CTIME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_TIME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##SCOTT"."COURSES" MODIFY ("COU_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table SCORE
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."SCORE" ADD CONSTRAINT "SCORE_COURSES_FK1" FOREIGN KEY ("COU_ID")
	  REFERENCES "C##SCOTT"."COURSES" ("COU_ID") ENABLE;
  ALTER TABLE "C##SCOTT"."SCORE" ADD CONSTRAINT "SCORE_STUDENTS_FK1" FOREIGN KEY ("STU_ID")
	  REFERENCES "C##SCOTT"."STUDENTS" ("STU_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COURSES
--------------------------------------------------------

  ALTER TABLE "C##SCOTT"."COURSES" ADD CONSTRAINT "COURSES_TEACHERS_FK1" FOREIGN KEY ("TEA_ID")
	  REFERENCES "C##SCOTT"."TEACHERS" ("TEA_ID") ENABLE;
  ALTER TABLE "C##SCOTT"."COURSES" ADD CONSTRAINT "COURSES_TYPES_FK1" FOREIGN KEY ("T_ID")
	  REFERENCES "C##SCOTT"."TYPE_" ("ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEL_TEA
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##SCOTT"."DEL_TEA" 
 before delete on teachers for each row
begin
  delete from courses where tea_id= :old.tea_id;
end;
/
ALTER TRIGGER "C##SCOTT"."DEL_TEA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRI_DM1
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##SCOTT"."TRI_DM1" 
 after insert on score for each row
begin
  update courses set cou_lnum = cou_lnum+1 where cou_id=:new.cou_id;
end;
/
ALTER TRIGGER "C##SCOTT"."TRI_DM1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEL_COU
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "C##SCOTT"."DEL_COU" 
 before delete on courses for each row
begin
  delete from score where cou_id = :old.cou_id;
end;
/
ALTER TRIGGER "C##SCOTT"."DEL_COU" ENABLE;
