/*
 * AddStudent.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Container;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import com.glxt.jdbc.Jdbc;
import com.glxt.jdbc.OperateOracle;
import com.glxt.model.Student;
import com.glxt.util.ClientConnect;

/**
 *
 * @author  __USER__
 */
public class AddStudent extends javax.swing.JFrame {

	/** Creates new form AddStudent */
	public AddStudent() {
		initComponents();
		ImageIcon img = new ImageIcon("img/yu.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel9 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jTextField1 = new javax.swing.JTextField();
		Is = new javax.swing.JComboBox();
		jComboBox2 = new javax.swing.JComboBox();
		jPasswordField1 = new javax.swing.JPasswordField();
		jComboBox1 = new javax.swing.JComboBox();
		jButton3 = new javax.swing.JButton();
		jTextField3 = new javax.swing.JTextField();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel9.setText("\u5bc6\u7801\uff1a");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel5.setText("\u73ed\u7ea7\uff1a");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel6.setText("\u4e13\u4e1a\uff1a");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel8.setText("\u5e74\u9f84\uff1a");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel7.setText("\u6027\u522b\uff1a");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel4.setText("\u5b66\u53f7\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jLabel3.setText("\u59d3\u540d\uff1a");

		jTextField2
				.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));

		jTextField1
				.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));

		Is.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		Is.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"计算机科学与技术", "通讯工程", "电气工程", "电子" }));
		Is.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				IsActionPerformed(evt);
			}
		});

		jComboBox2
				.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"一班", "二班", "三班", "四班", "五班", "六班", "七班", "八班" }));

		jPasswordField1.setFont(new java.awt.Font("Microsoft YaHei UI Light",
				1, 14));

		jComboBox1
				.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"男", "女" }));

		jButton3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));
		jButton3.setText("\u786e\u8ba4\u6dfb\u52a0");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jTextField3
				.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 14));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(184, 184, 184)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel5)
																						.addComponent(
																								jLabel6)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel7)
																						.addComponent(
																								jLabel4)
																						.addComponent(
																								jLabel3))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								178,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								178,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jComboBox2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								77,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								193,
																								Short.MAX_VALUE)
																						.addGroup(
																								layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING,
																												false)
																										.addComponent(
																												jTextField3,
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jComboBox1,
																												javax.swing.GroupLayout.Alignment.LEADING,
																												0,
																												64,
																												Short.MAX_VALUE))
																						.addComponent(
																								Is,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								149,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.Alignment.LEADING,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																243,
																Short.MAX_VALUE))
										.addGap(190, 190, 190)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(160, 160, 160)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel3))
										.addGap(15, 15, 15)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jTextField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4))
										.addGap(9, 9, 9)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																23,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7))
										.addGap(9, 9, 9)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(
																jTextField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(
																Is,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																21,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jComboBox2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																21,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9))
										.addGap(34, 34, 34).addComponent(
												jButton3).addContainerGap(191,
												Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents
	//确认添加按钮事件
	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String stu_name = jTextField1.getText();
		String stu_id = jTextField2.getText();
		String stu_pw = new String(jPasswordField1.getPassword());
		String stu_sex = jComboBox1.getSelectedItem().toString();
		String stu_major = Is.getSelectedItem().toString();
		String stu_class = jComboBox2.getSelectedItem().toString();
		int stu_age = 0;
		try {
			Integer.parseInt(stu_id);
			stu_age = Integer.parseInt(jTextField3.getText());
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, "学号和年龄不能为空并且必须是数字！");
		}
		if (stu_name == null || stu_name.isEmpty()) {
			JOptionPane tip = new JOptionPane();
			JOptionPane.showMessageDialog(this, "姓名不能为空！");
			tip.setVisible(true);
		} else if (stu_id == null || stu_id.isEmpty()) {
			JOptionPane tip = new JOptionPane();
			JOptionPane.showMessageDialog(this, "学号不能为空！");
			tip.setVisible(true);
		} else if (stu_pw == null || stu_pw.isEmpty()) {
			JOptionPane tip = new JOptionPane();
			JOptionPane.showMessageDialog(this, "密码不能为空！");
			tip.setVisible(true);
		}else if(!checkPassword(stu_pw)){
			JOptionPane.showMessageDialog(null, "密码必须为6-13的数字或者数字字母混合");
		}
		else {
			Student student = new Student(stu_id, stu_pw, stu_name, stu_sex,
					stu_age, stu_major, stu_class);
			if (new OperateOracle().addStudent(student)) {
				JOptionPane.showMessageDialog(this, "添加学生成功！");
			} else
				JOptionPane.showMessageDialog(this, "添加学生失败，请检查学号是否正确！");
		}
	}

	private void IsActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new AddStudent().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JComboBox Is;
	private javax.swing.JButton jButton3;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JTextField jTextField1;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	// End of variables declaration//GEN-END:variables
	public static boolean checkPassword(String pw){
		boolean flag = false;
		try{
		String check = "^[\\d|A-Za-z]{6,13}$";
		Pattern regex = Pattern.compile(check);
		Matcher matcher = regex.matcher(pw);
		flag = matcher.matches();
		}catch(Exception e){
		flag = false;
		}
		return flag;
	}
}