/*
 * AddScore.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Container;
import java.util.ArrayList;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

import com.glxt.jdbc.Jdbc;
import com.glxt.jdbc.OperateOracle;
import com.glxt.model.Score;
import com.glxt.model.Student;
import com.glxt.model.Teacher;
import com.glxt.util.ClientConnect;

/**
 *
 * @author  __USER__
 */
public class AddScore extends javax.swing.JFrame {

	/** Creates new form AddScore */
	Teacher teacher = null;
	TeaView teaview = null;

	public AddScore() {
		initComponents();
		ImageIcon img = new ImageIcon("img/yu.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

	public AddScore(TeaView teaview, Teacher teacher) {
		this.teacher = teacher;
		this.teaview = teaview;
		initComponents();
		ImageIcon img = new ImageIcon("img/yu.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		this.setLocationRelativeTo(null);
		init();
		this.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jScrollPane10 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton70 = new javax.swing.JButton();
		jButton83 = new javax.swing.JButton();
		jLabel77 = new javax.swing.JLabel();
		jTextField1 = new javax.swing.JTextField();
		jButton69 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null } }, new String[] {
						"课程ID", "课程名称", "学号", "姓名", "成绩" }) {
			Class[] types = new Class[] { java.lang.String.class,
					java.lang.String.class, java.lang.String.class,
					java.lang.String.class, java.lang.String.class };
			boolean[] canEdit = new boolean[] { false, false, false, false,
					true };

			public Class getColumnClass(int columnIndex) {
				return types[columnIndex];
			}

			public boolean isCellEditable(int rowIndex, int columnIndex) {
				return canEdit[columnIndex];
			}
		});
		jScrollPane10.setViewportView(jTable1);

		jButton70.setText("\u6dfb\u52a0");
		jButton70.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton70ActionPerformed(evt);
			}
		});

		jButton83.setText("\u5237\u65b0");
		jButton83.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton83ActionPerformed(evt);
			}
		});

		jLabel77.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18));
		jLabel77.setText("\u8f93\u5165\u8bfe\u7a0bID\u67e5\u627e\uff1a");

		jButton69.setText("\u786e\u5b9a");
		jButton69.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton69ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				174,
																				174,
																				174)
																		.addComponent(
																				jLabel77)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jTextField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				137,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton69,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				80,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				68,
																				68,
																				68)
																		.addComponent(
																				jScrollPane10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				584,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				216,
																				216,
																				216)
																		.addComponent(
																				jButton70,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				116,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				37,
																				37,
																				37)
																		.addComponent(
																				jButton83,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				116,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(78, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(123, 123, 123)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel77)
														.addComponent(
																jButton69,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																30,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jTextField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																30,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane10,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												303,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton70)
														.addComponent(jButton83))
										.addContainerGap(110, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		teaview.flush();
	}

	private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {
		String cou_id = jTextField1.getText();
		if (cou_id.isEmpty()) {
			JOptionPane.showMessageDialog(this, "课程ID不能为空！");
		} else {
			screen(cou_id);
		}
	}

	private void jButton83ActionPerformed(java.awt.event.ActionEvent evt) {
		flush();
	}

	private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {
		String tips = "";
		ArrayList<Score> scores = new ArrayList<Score>();
		System.out.println(jTable1.getRowCount());
		for (int j = 0; j < jTable1.getRowCount(); j++) {
			if (jTable1.getValueAt(j, 4) == null
					|| jTable1.getValueAt(j, 4).toString().length() == 0
					|| jTable1.getValueAt(j, 4).toString().equals("成绩未公布")) {

			} else if (Double.parseDouble(jTable1.getValueAt(j, 4).toString()) > 100
					|| Double.parseDouble(jTable1.getValueAt(j, 4).toString()) < 0) {
				tips = tips.concat(" 第" + j + "");
				break;
			}
		}
		if (tips.isEmpty()) {
			for (int i = 0; i < jTable1.getRowCount(); i++) {
				if (jTable1.getValueAt(i, 4) == null
						|| jTable1.getValueAt(i, 4).toString().length() == 0
						|| jTable1.getValueAt(i, 4).toString().equals("成绩未公布")) {
					for (int j = 0; j < teacher.getStudent().size(); j++) {
						if (teacher.getStudent().get(j).getId().equals(
								jTable1.getValueAt(i, 2).toString())) {
							for (int k = 0; k < teacher.getStudent().get(j)
									.getScores().size(); k++) {
								if ((teacher.getStudent().get(j).getScores()
										.get(k).getCourse_id() + "")
										.equals(jTable1.getValueAt(i, 0)
												.toString())) {
									Score score = new Score(Integer
											.parseInt(jTable1.getValueAt(i, 0)
													.toString()), Integer
											.parseInt(jTable1.getValueAt(i, 2)
													.toString()), -1);
									scores.add(score);
									break;
								}
							}
							break;
						}
					}
				} else {
					for (int j = 0; j < teacher.getStudent().size(); j++) {
						if (teacher.getStudent().get(j).getId().equals(
								jTable1.getValueAt(i, 2).toString())) {
							for (int k = 0; k < teacher.getStudent().get(j)
									.getScores().size(); k++) {
								if ((teacher.getStudent().get(j).getScores()
										.get(k).getCourse_id() + "")
										.equals(jTable1.getValueAt(i, 0)
												.toString())) {
									Score score = new Score(Integer
											.parseInt(jTable1.getValueAt(i, 0)
													.toString()), Integer
											.parseInt(jTable1.getValueAt(i, 2)
													.toString()), Double
											.parseDouble(jTable1.getValueAt(i,
													4).toString()));
									scores.add(score);
									break;
								}
							}
							break;
						}
					}
				}
			}
			System.out.println(scores.size());
			int i=0;
			try {
				for(;i<scores.size();i++){
					if(scores.get(i).getScore()==-1){
						if(!new OperateOracle().DelScore(scores.get(i).getCourse_id(), 
								scores.get(i).getStudent_id())){
							throw new RuntimeException("第"+i+"行数据修改失败");
						}
					}
					else{
						if(!new OperateOracle().SetScore(scores.get(i).getCourse_id(), 
								scores.get(i).getStudent_id(), scores.get(i).getScore())){
							throw new RuntimeException("第"+i+"行数据修改失败");
						}
					}
				}
				flush();
				JOptionPane.showMessageDialog(this, "添加成功！");
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, e.getMessage());
				System.out.println(e.getMessage());
			}
		} else {
			JOptionPane tip = new JOptionPane();
			JOptionPane.showMessageDialog(this, "" + tips + "行成绩不在0-100之间！");
			tip.setVisible(true);
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper
							.launchBeautyEyeLNF();

				} catch (Exception e) {

				}
				new AddScore().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton69;
	private javax.swing.JButton jButton70;
	private javax.swing.JButton jButton83;
	private javax.swing.JLabel jLabel77;
	private javax.swing.JScrollPane jScrollPane10;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextField jTextField1;

	// End of variables declaration//GEN-END:variables
	public void init() {
		initJtable(jTable1, ClientConnect.getteatable3(teacher));
	}

	public void screen(String cou_id) {
		initJtable(jTable1, ClientConnect.getteatable3(teacher, cou_id));
	}

	public void initJtable(JTable jtable, String[][] rowdata) {
		DefaultTableModel tableModel = (DefaultTableModel) jtable.getModel();
		tableModel.setRowCount(0);
		for (int i = 0; i < rowdata.length; i++) {
			tableModel.addRow(rowdata[i]);
		}
		jtable.invalidate();
	}

	public void flush() {
		teacher.setStudent(new OperateOracle().selectScore(teacher.getId(), null, 0));
		init();
	}
}