/*
 * StuDetails.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Container;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author  __USER__
 */
public class StuDetails extends javax.swing.JFrame {

	/** Creates new form StuDetails */
	public StuDetails(String text[]) {
		initComponents();
		ImageIcon img = new ImageIcon("img/stu123.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		JLabel jl[] = new JLabel[10];
		jl[0] = jLabel2;
		jl[1] = jLabel4;
		jl[2] = jLabel6;
		jl[3] = jLabel8;
		jl[4] = jLabel10;
		jl[5] = jLabel12;
		jl[6] = jLabel14;
		jl[7] = jLabel16;
		jl[8] = jLabel18;
		jl[9] = jLabel20;
		for (int i = 0; i < 10; i++) {
			jl[i].setText(text[i]);
		}
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

	public StuDetails() {
		initComponents();
		ImageIcon img = new ImageIcon("img/stu123.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		JLabel jl[] = new JLabel[10];
		jl[0] = jLabel2;
		jl[1] = jLabel4;
		jl[2] = jLabel6;
		jl[3] = jLabel8;
		jl[4] = jLabel10;
		jl[5] = jLabel12;
		jl[6] = jLabel14;
		jl[7] = jLabel16;
		jl[8] = jLabel18;
		jl[9] = jLabel20;
		this.setLocationRelativeTo(null);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel17 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
		setTitle("\u8bfe\u7a0b\u8be6\u60c5");

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel1.setText("\u8bfe \u7a0b  ID\uff1a");

		jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel2.setText("id");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel3.setText("\u8bfe\u7a0b\u540d\u79f0\uff1a");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel4.setText("\u540d\u79f0");

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel5.setText("\u4e0a\u8bfe\u671f\u9650\uff1a");

		jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel6.setText("\u671f\u9650");

		jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel7.setText("\u4e0a\u8bfe\u65f6\u95f4\uff1a");

		jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel8.setText("\u65f6\u95f4");

		jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel9.setText("\u4eba\u6570\u4e0a\u9650\uff1a");

		jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel10.setText("max");

		jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel11.setText("\u5df2\u9009\u4eba\u6570\uff1a");

		jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel12.setText("\u4eba\u6570");

		jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel13.setText("\u8bfe\u7a0b\u5b66\u5206\uff1a");

		jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel14.setText("\u5b66\u5206");

		jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel15.setText("\u4efb\u6559\u8001\u5e08\uff1a");

		jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel16.setText("\u8001\u5e08");

		jLabel17.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel17.setText("\u8bfe\u7a0b\u4f59\u91cf\uff1a");

		jLabel18.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel18.setText("\u4f59\u91cf");

		jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel19.setText("\u8bfe\u7a0b\u72b6\u6001\uff1a");

		jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18));
		jLabel20.setText("\u72b6\u6001");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(81, 81, 81)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(jLabel17)
														.addComponent(jLabel13)
														.addComponent(jLabel5)
														.addComponent(jLabel1)
														.addComponent(jLabel9))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel2)
														.addComponent(jLabel6)
														.addComponent(jLabel10)
														.addComponent(jLabel14)
														.addComponent(jLabel18))
										.addGap(87, 87, 87)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel19)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel20))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel15)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel16))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel11)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel12))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel4))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel7)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel8)))
										.addContainerGap(119, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(104, 104, 104)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(jLabel2)
														.addComponent(jLabel3)
														.addComponent(jLabel4))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(jLabel6)
														.addComponent(jLabel7)
														.addComponent(jLabel8))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel9)
														.addComponent(jLabel10)
														.addComponent(jLabel11)
														.addComponent(jLabel12))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel13)
														.addComponent(jLabel14)
														.addComponent(jLabel15)
														.addComponent(jLabel16))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel17)
														.addComponent(jLabel18)
														.addComponent(jLabel19)
														.addComponent(jLabel20))
										.addContainerGap(155, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper
							.launchBeautyEyeLNF();

				} catch (Exception e) {

				}
				new StuDetails().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel17;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	// End of variables declaration//GEN-END:variables

}