/*
 * TeaView.java
 *
 * Created on __DATE__, __TIME__
 */

package View;

import java.awt.Container;
import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

import com.glxt.jdbc.Jdbc;
import com.glxt.jdbc.OperateOracle;
import com.glxt.model.Course;
import com.glxt.model.Student;
import com.glxt.model.Teacher;
import com.glxt.util.ClientConnect;
import com.glxt.util.ViewUtils;

/**
 *
 * @author  __USER__
 */
public class TeaView extends javax.swing.JFrame {

	/** Creates new form TeaView */
	Teacher teacher = null;

	public TeaView(Teacher tea) {
		this.teacher = tea;
		initComponents();
		ImageIcon img = new ImageIcon("img/stu.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		this.setLocationRelativeTo(null);
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();

		} catch (Exception e) {

		}
		jLabel1.setText(teacher.getName() + "老师，欢迎你");
		init();
		//居中表格内容
		DefaultTableCellRenderer r = new DefaultTableCellRenderer();
		r.setHorizontalAlignment(JLabel.CENTER);
		jTable1.setDefaultRenderer(Object.class, r);
		jTable2.setDefaultRenderer(Object.class, r);
		jTable3.setDefaultRenderer(Object.class, r);
		jTable1.getTableHeader().setDefaultRenderer(r);
		jTable2.getTableHeader().setDefaultRenderer(r);
		jTable3.getTableHeader().setDefaultRenderer(r);
		this.setVisible(true);
	}

	public TeaView() {
		initComponents();
		ImageIcon img = new ImageIcon("img/stu.jpg");
		//要设置的背景图片  
		JLabel imgLabel = new JLabel(img);
		//将背景图放在标签里。  
		this.getLayeredPane().add(imgLabel, new Integer(Integer.MIN_VALUE));
		//将背景标签添加到jfram的LayeredPane面板里。  
		imgLabel.setBounds(0, 0, img.getIconWidth(), img.getIconHeight());
		//设置背景标签的位置  
		Container contain = this.getContentPane();
		((JPanel) contain).setOpaque(false);
		this.setLocationRelativeTo(null);
		try {
			org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper.launchBeautyEyeLNF();

		} catch (Exception e) {

		}
		DefaultTableCellRenderer r = new DefaultTableCellRenderer();
		r.setHorizontalAlignment(JLabel.CENTER);
		jTable1.setDefaultRenderer(Object.class, r);
		jTable2.setDefaultRenderer(Object.class, r);
		jTable3.setDefaultRenderer(Object.class, r);
		this.setVisible(true);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton5 = new javax.swing.JButton();
		jButton7 = new javax.swing.JButton();
		jButton8 = new javax.swing.JButton();
		jButton18 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jButton9 = new javax.swing.JButton();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable4 = new javax.swing.JTable();
		jButton22 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jButton23 = new javax.swing.JButton();
		jButton24 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jPanel4 = new javax.swing.JPanel();
		jButton13 = new javax.swing.JButton();
		jButton14 = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		jPasswordField3 = new javax.swing.JPasswordField();
		jPasswordField2 = new javax.swing.JPasswordField();
		jLabel4 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24));
		jLabel1.setText("XXX\u8001\u5e08\uff0c\u6b22\u8fce\u60a8");

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null },
						{ null, null, null, null, null, null } }, new String[] {
						"课程ID", "课程名称", "课程学分", "上课时间", "状态", "课程类型" }));
		jTable1.setOpaque(false);
		jScrollPane1.setViewportView(jTable1);

		jButton1.setText("\u6dfb\u52a0\u8bfe\u7a0b");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("\u5220\u9664\u8bfe\u7a0b");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jButton3.setText("\u67e5\u627e\u8bfe\u7a0b");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton3ActionPerformed(evt);
			}
		});

		jButton4.setText("\u4fee\u6539\u8bfe\u7a0b");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton4ActionPerformed(evt);
			}
		});

		jButton15.setText("\u6539\u53d8\u72b6\u6001");
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});

		jButton16.setText("\u5237\u65b0\u8bfe\u7a0b");
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jButton19.setText("\u67e5\u770b\u8bfe\u7a0b");
		jButton19.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton19ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												642, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addGroup(
																				jPanel1Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel1Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												jButton3)
																										.addComponent(
																												jButton16)
																										.addComponent(
																												jButton1))
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jButton4))
																		.addComponent(
																				jButton19))
														.addComponent(jButton15))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				353,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addGap(
																				24,
																				24,
																				24)
																		.addComponent(
																				jButton16)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton1)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton3)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton19)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton4)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton2)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton15)))
										.addContainerGap()));

		jTabbedPane1.addTab("\u8bfe\u7a0b\u7ba1\u7406", jPanel1);

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null } }, new String[] {
						"学号", "姓名", "性别", "专业", "班级" }));
		jScrollPane2.setViewportView(jTable2);

		jButton5.setText("\u67e5\u770b\u5b66\u751f");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton5ActionPerformed(evt);
			}
		});

		jButton7.setText("\u67e5\u627e\u5b66\u751f");
		jButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton7ActionPerformed(evt);
			}
		});

		jButton8.setText("\u589e\u52a0\u5b66\u751f");
		jButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton8ActionPerformed(evt);
			}
		});

		jButton18.setText("\u5237\u65b0\u5b66\u751f");
		jButton18.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton18ActionPerformed(evt);
			}
		});

		jButton21.setText("\u8bfe\u7a0b\u5b66\u751f");
		jButton21.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton21ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												642, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton5)
														.addComponent(jButton18)
														.addComponent(jButton7)
														.addComponent(jButton8)
														.addComponent(jButton21))
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				353,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addGap(
																				23,
																				23,
																				23)
																		.addComponent(
																				jButton18)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton5)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton7)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton8)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton21)))
										.addContainerGap()));

		jTabbedPane1.addTab("\u5b66\u751f\u7ba1\u7406", jPanel2);

		jTable3.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null },
						{ null, null, null, null, null } }, new String[] {
						"课程ID", "课程名称", "学生学号", "学生姓名", "成绩" }));
		jScrollPane3.setViewportView(jTable3);

		jButton9.setText("\u589e\u52a0\u6210\u7ee9");
		jButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton9ActionPerformed(evt);
			}
		});

		jButton10.setText("\u5220\u9664\u6210\u7ee9");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setText("\u67e5\u627e\u6210\u7ee9");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setText("\u4fee\u6539\u6210\u7ee9");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton12ActionPerformed(evt);
			}
		});

		jButton20.setText("\u5237\u65b0\u6210\u7ee9");
		jButton20.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton20ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												642, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jButton20)
																		.addComponent(
																				jButton9))
														.addComponent(jButton10)
														.addComponent(jButton11)
														.addComponent(jButton12))
										.addContainerGap()));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(
																				22,
																				22,
																				22)
																		.addComponent(
																				jButton20)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton9)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton10)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton11)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton12))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane3,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				353,
																				Short.MAX_VALUE)))
										.addContainerGap()));

		jTabbedPane1.addTab("\u6210\u7ee9\u7ba1\u7406", jPanel3);

		jTable4.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] {

				}, new String[] { "教师ID", "教师名称", "教师性别", "教师年龄" }));
		jScrollPane4.setViewportView(jTable4);

		jButton22.setText("\u5237\u65b0\u6559\u5e08");
		jButton22.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton22ActionPerformed(evt);
			}
		});

		jButton17.setText("\u589e\u52a0\u6559\u5e08");
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		jButton23.setText("\u5220\u9664\u6559\u5e08");
		jButton23.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton23ActionPerformed(evt);
			}
		});

		jButton24.setText("\u67e5\u627e\u6559\u5e08");
		jButton24.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton24ActionPerformed(evt);
			}
		});

		jButton6.setText("\u4fee\u6539\u6559\u5e08");
		jButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton6ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												642, Short.MAX_VALUE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jButton22)
														.addComponent(jButton17)
														.addComponent(jButton23)
														.addComponent(jButton24)
														.addComponent(jButton6))
										.addContainerGap()));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel5Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				jScrollPane4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				353,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGap(
																				22,
																				22,
																				22)
																		.addComponent(
																				jButton22)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton17)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton23)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton24)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jButton6)))
										.addContainerGap()));

		jTabbedPane1.addTab("\u6559\u5e08\u7ba1\u7406", jPanel5);

		jButton13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton13.setText("\u91cd\u7f6e");
		jButton13.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton13ActionPerformed(evt);
			}
		});

		jButton14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jButton14.setText("\u786e\u5b9a\u4fee\u6539");
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});

		jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel5.setText("\u8bf7\u518d\u6b21\u8f93\u5165\u5bc6\u7801\uff1a");

		jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel4.setText("\u8bf7\u8f93\u5165\u4fee\u6539\u5bc6\u7801\uff1a");

		jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14));
		jLabel3.setText("\u8bf7\u8f93\u5165\u539f\u59cb\u5bc6\u7801\uff1a");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout
										.createSequentialGroup()
										.addGap(242, 242, 242)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel3)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jPasswordField1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								216,
																								Short.MAX_VALUE))
																		.addGroup(
																				jPanel4Layout
																						.createSequentialGroup()
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jLabel4)
																										.addComponent(
																												jLabel5))
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												jPasswordField3,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												216,
																												Short.MAX_VALUE)
																										.addComponent(
																												jPasswordField2,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												216,
																												Short.MAX_VALUE))))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(
																				9,
																				9,
																				9)
																		.addComponent(
																				jButton14)
																		.addGap(
																				81,
																				81,
																				81)
																		.addComponent(
																				jButton13,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				97,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				58,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(198, 198, 198)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(105, 105, 105)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel3)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel4)
														.addComponent(
																jPasswordField2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel5)
														.addComponent(
																jPasswordField3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(43, 43, 43)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton14)
														.addComponent(jButton13))
										.addContainerGap(120, Short.MAX_VALUE)));

		jTabbedPane1.addTab("\u4fee\u6539\u5bc6\u7801", jPanel4);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addContainerGap(222,
						Short.MAX_VALUE).addGroup(
						layout.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jTabbedPane1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										779,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jLabel1)).addGap(175, 175, 175)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(137, 137, 137)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jTabbedPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												419,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(84, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable4.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个教师！");
		} else if (num == 1) {
			String[] tea = new String[4];
			tea[0] = jTable4.getValueAt(rows[0], 0).toString();
			tea[1] = jTable4.getValueAt(rows[0], 1).toString();
			tea[2] = jTable4.getValueAt(rows[0], 2).toString();
			tea[3] = jTable4.getValueAt(rows[0], 3).toString();

			new SetTeacher(tea);
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个教师！");
		}
	}

	private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {
		String input = JOptionPane.showInputDialog("请输入教师ID");
		System.out.println(input);
		if (input != null) {
			Integer.parseInt(input);
			String rows[][] = new OperateOracle().selectTeacher(input);
			if (rows.length != 0) {
				ViewUtils.initJTable(jTable4, rows);
			} else
				JOptionPane.showMessageDialog(this, "该教师不存在！");
		}
	}

	private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable4.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个课程！");
		} else if (num == 1) {
			int n = JOptionPane.showConfirmDialog(this, "确定要删除该教师？", "删除",
					JOptionPane.YES_NO_OPTION);
			if (n == 0) {
				String tea_id = jTable4.getValueAt(rows[0], 0).toString();
				if (new OperateOracle().deleteTeacher(tea_id)) {
					JOptionPane.showMessageDialog(this, "删除成功！");
					flush();
				} else
					JOptionPane.showMessageDialog(this, "删除失败！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个教师！");
		}
	}

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		new AddTeacher();
	}

	private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {
		ViewUtils.initJTable(jTable4, new OperateOracle().selectTeacher(null));
	}

	private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {
		teacher.setStudent(new OperateOracle().selectStudent(teacher.getId(), 2));
		initJtable(jTable2, ClientConnect.getteatable2(teacher));
	}

	private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {
		flushScore();
	}

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		new AddStudent();
	}

	private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {
		flushStudents();
	}

	private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {
		int row[] = jTable1.getSelectedRows();
		String cou[] = new String[2];
		if (row.length == 0) {
			JOptionPane.showMessageDialog(this, "没有选中课程！");
		} else if (row.length == 1) {
			cou[0] = jTable1.getValueAt(row[0], 0).toString();
			cou[1] = jTable1.getValueAt(row[0], 4).toString();
			String course[] = ClientConnect.getDeltail(teacher, cou);
			new StuDetails(course);
		} else
			JOptionPane.showMessageDialog(this, "不能同时选定两个以上的课程！");
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		flushCourses();
	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable1.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个课程！");
		} else if (num == 1) {
			int n = 0;
			String state = null;
			if (jTable1.getValueAt(rows[0], 4).toString().equals("授课中")) {
				n = JOptionPane.showConfirmDialog(this, "确定要结束该课程？", "结束",
						JOptionPane.YES_NO_OPTION);
				state = "已结课";
			} else {
				n = JOptionPane.showConfirmDialog(this, "确定要开启该课程？", "开启",
						JOptionPane.YES_NO_OPTION);
				state = "授课中";
			}
			if (n == 0) {
				String cou_id = jTable1.getValueAt(rows[0], 0).toString();
				Course course = new Course();
				course.setCourse_id(Integer.parseInt(cou_id));
				course.setState(state);
				if (new OperateOracle().setCourse(course.getCourse_id(), course.getState())) {
					JOptionPane.showMessageDialog(this, "修改成功！");
					flush();
				} else
					JOptionPane.showMessageDialog(this, "修改失败！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个课程！");
		}
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		String pass1 = new String(jPasswordField1.getPassword());
		String pass2 = new String(jPasswordField2.getPassword());
		String pass3 = new String(jPasswordField2.getPassword());
		if (pass2.equals(pass3)) {
			if (teacher.getPw().equals(pass1)) {
				try {
					if (new OperateOracle().setpw(teacher.getPw(), pass2, teacher.getId(),true)) {
						if (checkPassword(pass2)) {
							teacher.setPw(pass2);
							JOptionPane.showMessageDialog(this, "修改成功");
							jPasswordField1.setText("");
							jPasswordField2.setText("");
							jPasswordField3.setText("");
						} else {
							JOptionPane.showMessageDialog(null,
									"密码必须为6-13的数字或者数字字母混合");
						}
					} else {
						JOptionPane.showMessageDialog(this, "修改失败！");
						jPasswordField1.setText("");
						jPasswordField2.setText("");
						jPasswordField3.setText("");
					}
				} catch (Exception e) {
					// TODO: handle exception
				}
			} else
				JOptionPane.showMessageDialog(this, "原始密码错误");
		} else
			JOptionPane.showMessageDialog(this, "两次密码不一致");
	}

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {
		jPasswordField1.setText("");
		jPasswordField2.setText("");
		jPasswordField3.setText("");
	}

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable3.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个学生成绩！");
		} else if (num == 1) {
			String input = JOptionPane.showInputDialog("请输入该学生修改后的成绩");
			System.out.println(input);
			try {
				if (!(input == null || input.length() == 0)) {
					double score = Double.parseDouble(input);
					if (score < 0 || score > 100) {
						throw new RuntimeException("成绩超出上限");
					}
					int cou_id = Integer.parseInt(jTable3
							.getValueAt(rows[0], 0).toString());
					int stu_id = Integer.parseInt(jTable3
							.getValueAt(rows[0], 2).toString());
					if (new OperateOracle().SetScore(cou_id, stu_id, score)) {
						JOptionPane.showMessageDialog(this, "修改成功！");
						flushScore();
					} else
						JOptionPane.showMessageDialog(this, "修改失败！");
				}
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "学生成绩只能是数字，并且只能在0-100之间！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个课程！");
		}
	}

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {
		String input = JOptionPane.showInputDialog("请输入学生学号");
		System.out.println(input);
		if (input != null) {
			try {
				Integer.parseInt(input);
				//修改数据库操作
				teacher.setStudent(new OperateOracle().selectScore(teacher.getId()
						, input, 1));
				initJtable(jTable3, ClientConnect.getteatable3(teacher));
			} catch (Exception e) {
				e.printStackTrace();
				JOptionPane.showMessageDialog(this, "学生id只能是数字！");
			}
		}
	}

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {

		int rows[] = jTable3.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个课程！");
		} else if (num == 1) {
			int n = JOptionPane.showConfirmDialog(this, "确定要删除该学生成绩？", "删除",
					JOptionPane.YES_NO_OPTION);
			if (n == 0) {
				int cou_id = Integer.parseInt(jTable3.getValueAt(rows[0], 0)
						.toString());
				int stu_id = Integer.parseInt(jTable3.getValueAt(rows[0], 2)
						.toString());
				if (new OperateOracle().DelScore(cou_id, stu_id)) {
					JOptionPane.showMessageDialog(this, "删除成功！");
					flush();
				} else
					JOptionPane.showMessageDialog(this, "删除失败！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个课程！");
		}
	}

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		new AddScore(this, teacher).setVisible(true);
	}

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable1.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个课程！");
		} else if (num == 1) {
			Course course = null;
			ArrayList<Course> courses = teacher.getCourses();
			for (int i = 0; i < courses.size(); i++) {
				if (courses.get(i).getCourse_id() == Integer.parseInt(jTable1
						.getValueAt(rows[0], 0).toString())) {
					course = courses.get(i);
					break;
				}
			}
			new SetCourse(course, this);
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个课程！");
		}
	}

	private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		String input = JOptionPane.showInputDialog("请输入学生学号");
		System.out.println(input);
		//		String input = JOptionPane.showInputDialog("请输入课程编号");
		if (input != null) {
			try {
				Integer.parseInt(input);
				ArrayList<Student> student = new OperateOracle().selectStudent(input, 1);
				if (student == null||student.size()==0) {
					JOptionPane.showMessageDialog(this, "该学生不存在！");
				} else{
					teacher.setStudent(student);
					initJtable(jTable2, ClientConnect.getteatable2(teacher));
				}
			} catch (Exception e) {
				JOptionPane.showMessageDialog(this, "学生id只能是数字！");
			}
		}
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		int rows[] = jTable1.getSelectedRows();
		int num = rows.length;
		if (num == 0) {
			JOptionPane.showMessageDialog(this, "请选择一个课程！");
		} else if (num == 1) {
			int n = JOptionPane.showConfirmDialog(this, "确定要删除该课程？", "删除",
					JOptionPane.YES_NO_OPTION);
			if (n == 0) {
				String cou_id = jTable1.getValueAt(rows[0], 0).toString();
				if (new OperateOracle().deleteCourse(cou_id)) {
					JOptionPane.showMessageDialog(this, "删除成功！");
					flush();
				} else
					JOptionPane.showMessageDialog(this, "删除失败！");
			}
		} else {
			JOptionPane.showMessageDialog(this, "只能选择一个课程！");
		}
	}

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		String input = JOptionPane.showInputDialog("请输入课程编号，课程名称或者课程类别");
		ArrayList<Course> courses = null;
		if (input != null) {
			try {
				Integer.parseInt(input);
				courses = new OperateOracle().SelectTeaCourse(input, 1);

			} catch (Exception e) {
				courses = new OperateOracle().SelectTeaCourse(input, 2);
			}
			if (courses != null) {
				initJtable(jTable1, ClientConnect.getteatable1(courses));
			} else
				JOptionPane.showMessageDialog(this, "课程id不存在！");
		}
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		new AddCourse(teacher.getId(), this).setVisible(true);
	}

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		int row[] = jTable2.getSelectedRows();
		String cou_id = new String();
		if (row.length == 0) {
			JOptionPane.showMessageDialog(this, "没有选中课程！");
		} else if (row.length == 1) {
			cou_id = jTable2.getValueAt(row[0], 0).toString();
			String student[] = ClientConnect.getStuDeltail(teacher, cou_id);
			new StuData(student);
		} else
			JOptionPane.showMessageDialog(this, "不能同时选定两个以上的课程！");
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					org.jb2011.lnf.beautyeye.BeautyEyeLNFHelper
							.launchBeautyEyeLNF();

				} catch (Exception e) {

				}
				new TeaView().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton23;
	private javax.swing.JButton jButton24;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JButton jButton8;
	private javax.swing.JButton jButton9;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPasswordField jPasswordField1;
	private javax.swing.JPasswordField jPasswordField2;
	private javax.swing.JPasswordField jPasswordField3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable3;
	private javax.swing.JTable jTable4;

	// End of variables declaration//GEN-END:variables
	public void init() {
		initJtable(jTable1, ClientConnect.getteatable1(teacher));
		initJtable(jTable2, ClientConnect.getteatable2(teacher));
		initJtable(jTable3, ClientConnect.getteatable3(teacher));
	}

	public void initJtable(JTable jtable, String[][] rowdata) {
		DefaultTableModel tableModel = (DefaultTableModel) jtable.getModel();
		tableModel.setRowCount(0);
		for (int i = 0; i < rowdata.length; i++) {
			tableModel.addRow(rowdata[i]);
		}
		jtable.invalidate();
	}

	public void flush() {
		teacher.setCourses(new OperateOracle().SelectTeaCourse(null, 0));
		initJtable(jTable2, ClientConnect.getteatable2(teacher));
	}
	
	//刷新课程
	public void flushCourses() {
		teacher.setCourses(new OperateOracle().SelectTeaCourse(teacher.getId(), 0));
		initJtable(jTable1, ClientConnect.getteatable1(teacher));
	}
	
	//刷新学生
	public void flushStudents() {
		teacher.setStudent(new OperateOracle().selectStudent(null, 0));
		initJtable(jTable2, ClientConnect.getteatable2(teacher));
	}
	
	//刷新成绩
	public void flushScore() {
		teacher.setStudent(new OperateOracle().selectScore(teacher.getId(), null, 0));
		initJtable(jTable3, ClientConnect.getteatable3(teacher));
	}

	public static boolean checkPassword(String pw) {
		boolean flag = false;
		try {
			String check = "^[\\d|A-Za-z]{6,13}$";
			Pattern regex = Pattern.compile(check);
			Matcher matcher = regex.matcher(pw);
			flag = matcher.matches();
		} catch (Exception e) {
			flag = false;
		}
		return flag;
	}
}